hw-3 type script
Genesis-Front-End-School/clean-code-principes-yulyaolshanska pull request #4
Opened 2023-04-28 20:59 UTC by yulyaolshanska

2023-05-01 16:10 UTC, artemsukach approved these changes
Критичного нічого не знайшов. Так як я ще не добре знаю TypeScript то поки не знайшов нічого такого що можна покращити. Тому поки апрув, а в подальшому можливо знайду щось цікаве)

2023-05-01 16:10 UTC, artemsukach commented on src/components/App.tsx
> +      <Suspense fallback={(<Loader />) as React.ReactNode}>
|my opinion|
Я б імпортував ReactNode

2023-05-01 18:37 UTC, Markusplay requested changes

2023-05-01 18:37 UTC, Markusplay commented on src/pages/courseDetailsPage/CourseDetailsPage.tsx
> +            status={currentLesson.status === "locked" ? "locked" : "unlocked"}
You already have constant for "locked" status. Maybe shall write `currentLesson.status === LOCKED` ?

2023-05-01 18:48 UTC, Markusplay approved these changes

2023-05-01 18:49 UTC, merged

2023-05-05 15:32 UTC, vlad-khozhai commented on src/components/Pagination/Pagination.tsx
> +  const [currentPage, setCurrentPage] = useState<number>(1);
Если присваиваешь переменной примитивный тип, в этом случае это number, то ожно дополнительно тип не прописывать, например 
`const [currentPage, setCurrentPage] = useState(1);  // type will be number`
`const str = 'qwerty'; // type will be string`

2023-05-05 15:32 UTC, vlad-khozhai commented on src/components/VideoPlayer/VideoPlayer.tsx
> +}: VideoPlayerProps) => {
тип для пропсов передаем в дженерик в FC, дублировать тип не нужно